POCKET_CONSUMER_KEY = '{YOUR-OWN}'
POCKET_ACCESS_TOKEN = '{YOUR-OWN}'

TWITTER_CONSUMER_KEY = '{YOUR-OWN}'
TWITTER_CONSUMER_SECRET = '{YOUR-OWN}'
TWITTER_ACCESS_TOKEN_KEY = '{YOUR-OWN}'
TWITTER_ACCESS_TOKEN_SECRET = '{YOUR-OWN}'
